Lab2
afterbvrner/OOPLabs pull request #3
Opened 2020-10-07 15:50 UTC by MaksimGolish

Shop Manager

2020-10-07 19:02 UTC, InRedikaWB requested changes
Задача была на инкапсуляцию - с ней больше всего проблем.
+ эксепшены местами очень странно бросаются.

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/controller/ShopManager.java
> +                }
Ответственность магазина

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/controller/ShopManager.java
> +            } catch (ProductNotFoundException ignored){}
Это не ок, не нужно стоить логику на эксепшенах

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/controller/ShopManager.java
> +            throw new ProductNotFoundException(productId);
Что это и почему?

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/model/Shop.java
> +    public Long buy(ProductPack order) {
Почему этот метод так называется?

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/model/Shop.java
> +            }
Зачем?

2020-10-07 19:02 UTC, FrediKats commented on Shop/src/main/java/model/Shop.java
> +            if(product.getValue().getKey()<=price && product.getValue().getValue()!=0)
Пробелы?

2020-10-07 19:02 UTC, InRedikaWB commented on Shop/src/main/java/model/Shop.java
> +        }
Что это?..

2020-10-07 19:14 UTC, MaksimGolish commented on Shop/src/main/java/model/Shop.java
> +        }
> Что это?..

Если продуктов достаточно, то добавляем в пак на всю сумму. Если меньше, то добавляем сколько есть

2020-10-07 19:18 UTC, MaksimGolish commented on Shop/src/main/java/controller/ShopManager.java
> +            throw new ProductNotFoundException(productId);
Если в лист не добавлен ни один магазин, то такой товар не найден. Кидаем эксепшон

2020-10-08 07:35 UTC, maxgolish commented on Shop/src/main/java/controller/ShopManager.java
> +                }
> Ответственность магазина

Это ж сравнение цены со всеми магазинами, это не может быть ответственностью магазина

2020-10-17 22:14 UTC, FrediKats commented on Shop/src/main/java/model/Shop.java
> +        }
Вынес бы в метод, чтобы вызывающий код мог проверять, а не только по эксепшену определять все ли ок,

2020-10-17 22:14 UTC, FrediKats commented
В остальном ок.

2020-10-19 14:59 UTC, FrediKats approved these changes

2020-10-19 18:00 UTC, merged